<a href="https://colab.research.google.com/github/NikolaiMi/portfolio/blob/master/%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D1%87_%D1%81_%D1%81%D0%B0%D0%B9%D1%82%D0%B0_sql_ex_ru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 30+ задач с сайта sql-ex.ru
Привет!

Идею для этого блокнота предложил куратор курса аналитики данных Глеб Михайлов.

Здесь я покажу, как решал задачи на самом популярном сайте про SQL.

Постепенно я буду пополнять блокнот новыми задачами.

Чтобы не казалось, что все это простая копипаста (ну а вдруг), я буду сопровождать каждое решение своими комментариями, в которых покажу, как рассуждал при решении.

## Создаем базу с данными sql-ex

Тут ничего интересного, поэтому раздел специально свернут.

Этот скрипт можно скачать у них на https://sql-ex.ru/db_script_download.php. Это конкретно https://sql-ex.ru/download/sql-ex-pg.sql, все таблицы одним скриптом для postgres.

In [ ]:
sql = '''drop table if exists pass_in_trip;
drop table if exists trip;
drop table if exists passenger;
drop table if exists company;

--
CREATE TABLE Company (
	ID_comp int NOT NULL ,
	name char (10) NOT NULL 
)
;

CREATE TABLE Pass_in_trip (
	trip_no int NOT NULL ,
	date timestamp NOT NULL ,
	ID_psg int NOT NULL ,
	place char (10) NOT NULL 
)
;

CREATE TABLE Passenger (
	ID_psg int NOT NULL ,
	name char (20) NOT NULL 
)
;

CREATE TABLE Trip (
	trip_no int NOT NULL ,
	ID_comp int NOT NULL ,
	plane char (10) NOT NULL ,
	town_from char (25) NOT NULL ,
	town_to char (25) NOT NULL ,
	time_out timestamp NOT NULL ,
	time_in timestamp NOT NULL 
)
;

                                                                                                                                                                                                                                                                 
----Company------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Company values(1,'Don_avia  ');
insert into Company values(2,'Aeroflot  ');
insert into Company values(3,'Dale_avia ');
insert into Company values(4,'air_France');
insert into Company values(5,'British_AW');


                                                                                                                                                                                                                                                                 
----Passenger------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Passenger values(1,'Bruce Willis        ');
insert into Passenger values(2,'George Clooney      ');
insert into Passenger values(3,'Kevin Costner       ');
insert into Passenger values(4,'Donald Sutherland   ');
insert into Passenger values(5,'Jennifer Lopez      ');
insert into Passenger values(6,'Ray Liotta          ');
insert into Passenger values(7,'Samuel L. Jackson   ');
insert into Passenger values(8,'Nikole Kidman       ');
insert into Passenger values(9,'Alan Rickman        ');
insert into Passenger values(10,'Kurt Russell        ');
insert into Passenger values(11,'Harrison Ford       ');
insert into Passenger values(12,'Russell Crowe       ');
insert into Passenger values(13,'Steve Martin        ');
insert into Passenger values(14,'Michael Caine       ');
insert into Passenger values(15,'Angelina Jolie      ');
insert into Passenger values(16,'Mel Gibson          ');
insert into Passenger values(17,'Michael Douglas     ');
insert into Passenger values(18,'John Travolta       ');
insert into Passenger values(19,'Sylvester Stallone  ');
insert into Passenger values(20,'Tommy Lee Jones     ');
insert into Passenger values(21,'Catherine Zeta-Jones');
insert into Passenger values(22,'Antonio Banderas    ');
insert into Passenger values(23,'Kim Basinger        ');
insert into Passenger values(24,'Sam Neill           ');
insert into Passenger values(25,'Gary Oldman         ');
insert into Passenger values(26,'Clint Eastwood      ');
insert into Passenger values(27,'Brad Pitt           ');
insert into Passenger values(28,'Johnny Depp         ');
insert into Passenger values(29,'Pierce Brosnan      ');
insert into Passenger values(30,'Sean Connery        ');
insert into Passenger values(31,'Bruce Willis        ');
insert into Passenger values(37,'Mullah Omar         ');



                                                                                                                                                                                                                                                                 
----Trip------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Trip values(1100,4,'Boeing    ','Rostov                   ','Paris                    ','19000101 14:30:00.000','19000101 17:50:00.000');
insert into Trip values(1101,4,'Boeing    ','Paris                    ','Rostov                   ','19000101 08:12:00.000','19000101 11:45:00.000');
insert into Trip values(1123,3,'TU-154    ','Rostov                   ','Vladivostok              ','19000101 16:20:00.000','19000101 03:40:00.000');
insert into Trip values(1124,3,'TU-154    ','Vladivostok              ','Rostov                   ','19000101 09:00:00.000','19000101 19:50:00.000');
insert into Trip values(1145,2,'IL-86     ','Moscow                   ','Rostov                   ','19000101 09:35:00.000','19000101 11:23:00.000');
insert into Trip values(1146,2,'IL-86     ','Rostov                   ','Moscow                   ','19000101 17:55:00.000','19000101 20:01:00.000');
insert into Trip values(1181,1,'TU-134    ','Rostov                   ','Moscow                   ','19000101 06:12:00.000','19000101 08:01:00.000');
insert into Trip values(1182,1,'TU-134    ','Moscow                   ','Rostov                   ','19000101 12:35:00.000','19000101 14:30:00.000');
insert into Trip values(1187,1,'TU-134    ','Rostov                   ','Moscow                   ','19000101 15:42:00.000','19000101 17:39:00.000');
insert into Trip values(1188,1,'TU-134    ','Moscow                   ','Rostov                   ','19000101 22:50:00.000','19000101 00:48:00.000');
insert into Trip values(1195,1,'TU-154    ','Rostov                   ','Moscow                   ','19000101 23:30:00.000','19000101 01:11:00.000');
insert into Trip values(1196,1,'TU-154    ','Moscow                   ','Rostov                   ','19000101 04:00:00.000','19000101 05:45:00.000');
insert into Trip values(7771,5,'Boeing    ','London                   ','Singapore                ','19000101 01:00:00.000','19000101 11:00:00.000');
insert into Trip values(7772,5,'Boeing    ','Singapore                ','London                   ','19000101 12:00:00.000','19000101 02:00:00.000');
insert into Trip values(7773,5,'Boeing    ','London                   ','Singapore                ','19000101 03:00:00.000','19000101 13:00:00.000');
insert into Trip values(7774,5,'Boeing    ','Singapore                ','London                   ','19000101 14:00:00.000','19000101 06:00:00.000');
insert into Trip values(7775,5,'Boeing    ','London                   ','Singapore                ','19000101 09:00:00.000','19000101 20:00:00.000');
insert into Trip values(7776,5,'Boeing    ','Singapore                ','London                   ','19000101 18:00:00.000','19000101 08:00:00.000');
insert into Trip values(7777,5,'Boeing    ','London                   ','Singapore                ','19000101 18:00:00.000','19000101 06:00:00.000');
insert into Trip values(7778,5,'Boeing    ','Singapore                ','London                   ','19000101 22:00:00.000','19000101 12:00:00.000');
insert into Trip values(8881,5,'Boeing    ','London                   ','Paris                    ','19000101 03:00:00.000','19000101 04:00:00.000');
insert into Trip values(8882,5,'Boeing    ','Paris                    ','London                   ','19000101 22:00:00.000','19000101 23:00:00.000');



                                                                                                                                                                                                                                                                 
----Pass_in_trip------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Pass_in_trip values(1100,'20030429 00:00:00.000',1,'1a        ');
insert into Pass_in_trip values(1123,'20030405 00:00:00.000',3,'2a        ');
insert into Pass_in_trip values(1123,'20030408 00:00:00.000',1,'4c        ');
insert into Pass_in_trip values(1123,'20030408 00:00:00.000',6,'4b        ');
insert into Pass_in_trip values(1124,'20030402 00:00:00.000',2,'2d        ');
insert into Pass_in_trip values(1145,'20030405 00:00:00.000',3,'2c        ');
insert into Pass_in_trip values(1181,'20030401 00:00:00.000',1,'1a        ');
insert into Pass_in_trip values(1181,'20030401 00:00:00.000',6,'1b        ');
insert into Pass_in_trip values(1181,'20030401 00:00:00.000',8,'3c        ');
insert into Pass_in_trip values(1181,'20030413 00:00:00.000',5,'1b        ');
insert into Pass_in_trip values(1182,'20030413 00:00:00.000',5,'4b        ');
insert into Pass_in_trip values(1187,'20030414 00:00:00.000',8,'3a        ');
insert into Pass_in_trip values(1188,'20030401 00:00:00.000',8,'3a        ');
insert into Pass_in_trip values(1182,'20030413 00:00:00.000',9,'6d        ');
insert into Pass_in_trip values(1145,'20030425 00:00:00.000',5,'1d        ');
insert into Pass_in_trip values(1187,'20030414 00:00:00.000',10,'3d        ');
insert into Pass_in_trip values(8882,'20051106 00:00:00.000',37,'1a        ') ;
insert into Pass_in_trip values(7771,'20051107 00:00:00.000',37,'1c        ') ;
insert into Pass_in_trip values(7772,'20051107 00:00:00.000',37,'1a        ') ;
insert into Pass_in_trip values(8881,'20051108 00:00:00.000',37,'1d        ') ;
insert into Pass_in_trip values(7778,'20051105 00:00:00.000',10,'2a        ') ;
insert into Pass_in_trip values(7772,'20051129 00:00:00.000',10,'3a        ');
insert into Pass_in_trip values(7771,'20051104 00:00:00.000',11,'4a        ');
insert into Pass_in_trip values(7771,'20051107 00:00:00.000',11,'1b        ');
insert into Pass_in_trip values(7771,'20051109 00:00:00.000',11,'5a        ');
insert into Pass_in_trip values(7772,'20051107 00:00:00.000',12,'1d        ');
insert into Pass_in_trip values(7773,'20051107 00:00:00.000',13,'2d        ');
insert into Pass_in_trip values(7772,'20051129 00:00:00.000',13,'1b        ');
insert into Pass_in_trip values(8882,'20051113 00:00:00.000',14,'3d        ');
insert into Pass_in_trip values(7771,'20051114 00:00:00.000',14,'4d        ');
insert into Pass_in_trip values(7771,'20051116 00:00:00.000',14,'5d        ');
insert into Pass_in_trip values(7772,'20051129 00:00:00.000',14,'1c        ');

drop table if exists Laptop;
drop table if exists PC;
drop table if exists Printer;
drop table if exists Product;

CREATE TABLE Laptop (
	code int NOT NULL ,
	model varchar (50) NOT NULL ,
	speed smallint NOT NULL ,
	ram smallint NOT NULL ,
	hd real NOT NULL ,
	price decimal(12,2) NULL ,
	screen smallint NOT NULL 
) 
;

CREATE TABLE PC (
	code int NOT NULL ,
	model varchar (50) NOT NULL ,
	speed smallint NOT NULL ,
	ram smallint NOT NULL ,
	hd real NOT NULL ,
	cd varchar (10) NOT NULL ,
	price decimal(12,2) NULL 
) 
;

CREATE TABLE Product (
	maker varchar (10) NOT NULL ,
	model varchar (50) NOT NULL ,
	type varchar (50) NOT NULL 
) 
;

CREATE TABLE Printer (
	code int NOT NULL ,
	model varchar (50) NOT NULL ,
	color char (1) NOT NULL ,
	type varchar (10) NOT NULL ,
	price decimal(12,2) NULL 
) 
;

----Product------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Product values('B','1121','PC');
insert into Product values('A','1232','PC');
insert into Product values('A','1233','PC');
insert into Product values('E','1260','PC');
insert into Product values('A','1276','Printer');
insert into Product values('D','1288','Printer');
insert into Product values('A','1298','Laptop');
insert into Product values('C','1321','Laptop');
insert into Product values('A','1401','Printer');
insert into Product values('A','1408','Printer');
insert into Product values('D','1433','Printer');
insert into Product values('E','1434','Printer');
insert into Product values('B','1750','Laptop');
insert into Product values('A','1752','Laptop');
insert into Product values('E','2113','PC');
insert into Product values('E','2112','PC');
                                                                                                                                                                                                                                                                 
----PC------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into PC values(1,'1232',500,64,5,'12x','600');
insert into PC values(2,'1121',750,128,14,'40x','850');
insert into PC values(3,'1233',500,64,5,'12x','600');
insert into PC values(4,'1121',600,128,14,'40x','850');
insert into PC values(5,'1121',600,128,8,'40x','850');
insert into PC values(6,'1233',750,128,20,'50x','950');
insert into PC values(7,'1232',500,32,10,'12x','400');
insert into PC values(8,'1232',450,64,8,'24x','350');
insert into PC values(9,'1232',450,32,10,'24x','350');
insert into PC values(10,'1260',500,32,10,'12x','350');
insert into PC values(11,'1233',900,128,40,'40x','980');
insert into PC values(12,'1233',800,128,20,'50x','970');

                                                                                                                                                                                                                                                                 
----Laptop------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Laptop values(1,'1298',350,32,4,'700',11);
insert into Laptop values(2,'1321',500,64,8,'970',12);
insert into Laptop values(3,'1750',750,128,12,'1200',14);
insert into Laptop values(4,'1298',600,64,10,'1050',15);
insert into Laptop values(5,'1752',750,128,10,'1150',14);
insert into Laptop values(6,'1298',450,64,10,'950',12);

                                                                                                                                                                                                                                                                 
----Printer------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Printer values(1,'1276','n','Laser','400');
insert into Printer values(2,'1433','y','Jet','270');
insert into Printer values(3,'1434','y','Jet','290');
insert into Printer values(4,'1401','n','Matrix','150');
insert into Printer values(5,'1408','n','Matrix','270');
insert into Printer values(6,'1288','n','Laser','400');

-- select * from income
drop table if exists Income;
drop table if exists Outcome;
drop table if exists Outcome_o;
drop table if exists Income_o;

CREATE TABLE Income (
	code int NOT NULL ,
	point smallint NOT NULL ,
	date timestamp NOT NULL ,
	inc decimal(12,2) NOT NULL 
) 
;

CREATE TABLE Outcome (
	code int NOT NULL ,
	point smallint NOT NULL ,
	date timestamp NOT NULL ,
	out decimal(12,2) NOT NULL 
) 
;

CREATE TABLE Income_o (
	point smallint NOT NULL ,
	date timestamp NOT NULL ,
	inc decimal(12,2) NOT NULL 
) 
;

CREATE TABLE Outcome_o (
	point smallint NOT NULL ,
	date timestamp NOT NULL ,
	out decimal(12,2) NOT NULL 
) 
;
                                                                                                                                                                                                                                                                 
----Income------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Income values(1,1,'20010322 00:00:00.000','15000.00');
insert into Income values(2,1,'20010323 00:00:00.000','15000.00');
insert into Income values(3,1,'20010324 00:00:00.000','3600.00');
insert into Income values(4,2,'20010322 00:00:00.000','10000.00');
insert into Income values(5,2,'20010324 00:00:00.000','1500.00');
insert into Income values(6,1,'20010413 00:00:00.000','5000.00');
insert into Income values(7,1,'20010511 00:00:00.000','4500.00');
insert into Income values(8,1,'20010322 00:00:00.000','15000.00');
insert into Income values(9,2,'20010324 00:00:00.000','1500.00');
insert into Income values(10,1,'20010413 00:00:00.000','5000.00');
insert into Income values(11,1,'20010324 00:00:00.000','3400.00');
insert into Income values(12,3,'20010913 00:00:00.000','1350.00');
insert into Income values(13,3,'20010913 00:00:00.000','1750.00');

                                                                                                                                                                                                                                                                 
---------Outcome-----------------
insert into Outcome values(1,1,'20010314 00:00:00.000','15348.00');
insert into Outcome values(2,1,'20010324 00:00:00.000','3663.00');
insert into Outcome values(3,1,'20010326 00:00:00.000','1221.00');
insert into Outcome values(4,1,'20010328 00:00:00.000','2075.00');
insert into Outcome values(5,1,'20010329 00:00:00.000','2004.00');
insert into Outcome values(6,1,'20010411 00:00:00.000','3195.04');
insert into Outcome values(7,1,'20010413 00:00:00.000','4490.00');
insert into Outcome values(8,1,'20010427 00:00:00.000','3110.00');
insert into Outcome values(9,1,'20010511 00:00:00.000','2530.00');
insert into Outcome values(10,2,'20010322 00:00:00.000','1440.00');
insert into Outcome values(11,2,'20010329 00:00:00.000','7848.00');
insert into Outcome values(12,2,'20010402 00:00:00.000','2040.00');
insert into Outcome values(13,1,'20010324 00:00:00.000','3500.00');
insert into Outcome values(14,2,'20010322 00:00:00.000','1440.00');
insert into Outcome values(15,1,'20010329 00:00:00.000','2006.00');
insert into Outcome values(16,3,'20010913 00:00:00.000','1200.00');
insert into Outcome values(17,3,'20010913 00:00:00.000','1500.00');
insert into Outcome values(18,3,'20010914 00:00:00.000','1150.00');

                                                                                                                                                                                                                                                                 
--------Income_o --------------
insert into Income_o values(1,'20010322 00:00:00.000','15000.00');
insert into Income_o values(1,'20010323 00:00:00.000','15000.00');
insert into Income_o values(1,'20010324 00:00:00.000','3400.00');
insert into Income_o values(1,'20010413 00:00:00.000','5000.00');
insert into Income_o values(1,'20010511 00:00:00.000','4500.00');
insert into Income_o values(2,'20010322 00:00:00.000','10000.00');
insert into Income_o values(2,'20010324 00:00:00.000','1500.00');
insert into Income_o values(3,'20010913 00:00:00.000','11500.00');
insert into Income_o values(3,'20011002 00:00:00.000','18000.00');


                                                                                                                                                                                                                                                                 
---------Outcome_o -----------
insert into Outcome_o values(1,'20010314 00:00:00.000','15348');
insert into Outcome_o values(1,'20010324 00:00:00.000','3663');
insert into Outcome_o values(1,'20010326 00:00:00.000','1221');
insert into Outcome_o values(1,'20010328 00:00:00.000','2075');
insert into Outcome_o values(1,'20010329 00:00:00.000','2004');
insert into Outcome_o values(1,'20010411 00:00:00.000','3195.04');
insert into Outcome_o values(1,'20010413 00:00:00.000','4490');
insert into Outcome_o values(1,'20010427 00:00:00.000','3110');
insert into Outcome_o values(1,'20010511 00:00:00.000','2530');
insert into Outcome_o values(2,'20010322 00:00:00.000','1440');
insert into Outcome_o values(2,'20010329 00:00:00.000','7848');
insert into Outcome_o values(2,'20010402 00:00:00.000','2040');
insert into Outcome_o values(3,'20010913 00:00:00.000','1500');
insert into Outcome_o values(3,'20010914 00:00:00.000','2300');
insert into Outcome_o values(3,'20020916 00:00:00.000','2150');


drop table if exists utb;
drop table if exists utq;
drop table if exists utv;
--
CREATE TABLE utB (
	B_DATETIME timestamp NOT NULL ,
	B_Q_ID int NOT NULL ,
	B_V_ID int NOT NULL ,
	B_VOL smallint NULL 
) 
;

CREATE TABLE utQ (
	Q_ID int NOT NULL ,
	Q_NAME varchar (35) NOT NULL 
) 
;

CREATE TABLE utV (
	V_ID int NOT NULL ,
	V_NAME varchar (35) NOT NULL ,
	V_COLOR char (1) NOT NULL 
) 
;

                                                                                                                                                                                                                                                                
----utQ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into utQ values(1,'Square # 01');
insert into utQ values(2,'Square # 02');
insert into utQ values(3,'Square # 03');
insert into utQ values(4,'Square # 04');
insert into utQ values(5,'Square # 05');
insert into utQ values(6,'Square # 06');
insert into utQ values(7,'Square # 07');
insert into utQ values(8,'Square # 08');
insert into utQ values(9,'Square # 09');
insert into utQ values(10,'Square # 10');
insert into utQ values(11,'Square # 11');
insert into utQ values(12,'Square # 12');
insert into utQ values(13,'Square # 13');
insert into utQ values(14,'Square # 14');
insert into utQ values(15,'Square # 15');
insert into utQ values(16,'Square # 16');
insert into utQ values(17,'Square # 17');
insert into utQ values(18,'Square # 18');
insert into utQ values(19,'Square # 19');
insert into utQ values(20,'Square # 20');
insert into utQ values(21,'Square # 21');
insert into utQ values(22,'Square # 22');
insert into utQ values(23,'Square # 23');
insert into utQ values(25,'Square # 25');



                                                                                                                                                                                                                                                                 
----utV------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into utV values(1,'Balloon # 01','R');
insert into utV values(2,'Balloon # 02','R');
insert into utV values(3,'Balloon # 03','R');
insert into utV values(4,'Balloon # 04','G');
insert into utV values(5,'Balloon # 05','G');
insert into utV values(6,'Balloon # 06','G');
insert into utV values(7,'Balloon # 07','B');
insert into utV values(8,'Balloon # 08','B');
insert into utV values(9,'Balloon # 09','B');
insert into utV values(10,'Balloon # 10','R');
insert into utV values(11,'Balloon # 11','R');
insert into utV values(12,'Balloon # 12','R');
insert into utV values(13,'Balloon # 13','G');
insert into utV values(14,'Balloon # 14','G');
insert into utV values(15,'Balloon # 15','B');
insert into utV values(16,'Balloon # 16','B');
insert into utV values(17,'Balloon # 17','R');
insert into utV values(18,'Balloon # 18','G');
insert into utV values(19,'Balloon # 19','B');
insert into utV values(20,'Balloon # 20','R');
insert into utV values(21,'Balloon # 21','G');
insert into utV values(22,'Balloon # 22','B');
insert into utV values(23,'Balloon # 23','R');
insert into utV values(24,'Balloon # 24','G');
insert into utV values(25,'Balloon # 25','B');
insert into utV values(26,'Balloon # 26','B');
insert into utV values(27,'Balloon # 27','R');
insert into utV values(28,'Balloon # 28','G');
insert into utV values(29,'Balloon # 29','R');
insert into utV values(30,'Balloon # 30','G');
insert into utV values(31,'Balloon # 31','R');
insert into utV values(32,'Balloon # 32','G');
insert into utV values(33,'Balloon # 33','B');
insert into utV values(34,'Balloon # 34','R');
insert into utV values(35,'Balloon # 35','G');
insert into utV values(36,'Balloon # 36','B');
insert into utV values(37,'Balloon # 37','R');
insert into utV values(38,'Balloon # 38','G');
insert into utV values(39,'Balloon # 39','B');
insert into utV values(40,'Balloon # 40','R');
insert into utV values(41,'Balloon # 41','R');
insert into utV values(42,'Balloon # 42','G');
insert into utV values(43,'Balloon # 43','B');
insert into utV values(44,'Balloon # 44','R');
insert into utV values(45,'Balloon # 45','G');
insert into utV values(46,'Balloon # 46','B');
insert into utV values(47,'Balloon # 47','B');
insert into utV values(48,'Balloon # 48','G');
insert into utV values(49,'Balloon # 49','R');
insert into utV values(50,'Balloon # 50','G');
insert into utV values(51,'Balloon # 51','B');
insert into utV values(52,'Balloon # 52','R');
insert into utV values(53,'Balloon # 53','G');
insert into utV values(54,'Balloon # 54','B');

                                                                                                                                                                                                                                                                 
----utB------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into utB values('20030101 01:12:01.000',1,1,155);
insert into utB values('20030623 01:12:02.000',1,1,100);
insert into utB values('20030101 01:12:03.000',2,2,255);
insert into utB values('20030101 01:12:04.000',3,3,255);
insert into utB values('20030101 01:12:05.000',1,4,255);
insert into utB values('20030101 01:12:06.000',2,5,255);
insert into utB values('20030101 01:12:07.000',3,6,255);
insert into utB values('20030101 01:12:08.000',1,7,255);
insert into utB values('20030101 01:12:09.000',2,8,255);
insert into utB values('20030101 01:12:10.000',3,9,255);
insert into utB values('20030101 01:12:11.000',4,10,50);
insert into utB values('20030101 01:12:12.000',5,11,100);
insert into utB values('20030101 01:12:13.000',5,12,155);
insert into utB values('20030101 01:12:14.000',5,13,155);
insert into utB values('20030101 01:12:15.000',5,14,100);
insert into utB values('20030101 01:12:16.000',5,15,50);
insert into utB values('20030101 01:12:17.000',5,16,205);
insert into utB values('20030101 01:12:18.000',6,10,155);
insert into utB values('20030101 01:12:19.000',6,17,100);
insert into utB values('20030101 01:12:20.000',6,18,255);
insert into utB values('20030101 01:12:21.000',6,19,255);
insert into utB values('20030101 01:12:22.000',7,17,155);
insert into utB values('20030101 01:12:23.000',7,20,100);
insert into utB values('20030101 01:12:24.000',7,21,255);
insert into utB values('20030101 01:12:25.000',7,22,255);
insert into utB values('20030101 01:12:26.000',8,10,50);
insert into utB values('20030101 01:12:27.000',9,23,255);
insert into utB values('20030101 01:12:28.000',9,24,255);
insert into utB values('20030101 01:12:29.000',9,25,100);
insert into utB values('20030101 01:12:30.000',9,26,155);
insert into utB values('20030101 01:12:31.000',10,25,155);
insert into utB values('20030101 01:12:31.000',10,26,100);
insert into utB values('20030101 01:12:33.000',10,27,10);
insert into utB values('20030101 01:12:34.000',10,28,10);
insert into utB values('20030101 01:12:35.000',10,29,245);
insert into utB values('20030101 01:12:36.000',10,30,245);
insert into utB values('20030101 01:12:37.000',11,31,100);
insert into utB values('20030101 01:12:38.000',11,32,100);
insert into utB values('20030101 01:12:39.000',11,33,100);
insert into utB values('20030101 01:12:40.000',11,34,155);
insert into utB values('20030101 01:12:41.000',11,35,155);
insert into utB values('20030101 01:12:42.000',11,36,155);
insert into utB values('20030101 01:12:43.000',12,31,155);
insert into utB values('20030101 01:12:44.000',12,32,155);
insert into utB values('20030101 01:12:45.000',12,33,155);
insert into utB values('20030101 01:12:46.000',12,34,100);
insert into utB values('20030101 01:12:47.000',12,35,100);
insert into utB values('20030101 01:12:48.000',12,36,100);
insert into utB values('20030101 01:13:01.000',4,37,20);
insert into utB values('20030101 01:13:02.000',8,38,20);
insert into utB values('20030101 01:13:03.000',13,39,123);
insert into utB values('20030101 01:13:04.000',14,39,111);
insert into utB values('20030101 01:13:05.000',14,40,50);
insert into utB values('20030101 01:13:06.000',15,41,50);
insert into utB values('20030101 01:13:07.000',15,41,50);
insert into utB values('20030101 01:13:08.000',15,42,50);
insert into utB values('20030101 01:13:09.000',15,42,50);
insert into utB values('20030101 01:13:10.000',16,42,50);
insert into utB values('20030101 01:13:11.000',16,42,50);
insert into utB values('20030101 01:13:12.000',16,43,50);
insert into utB values('20030101 01:13:13.000',16,43,50);
insert into utB values('20030101 01:13:14.000',16,47,50);
insert into utB values('20030101 01:13:15.000',17,44,10);
insert into utB values('20030101 01:13:16.000',17,44,10);
insert into utB values('20030101 01:13:17.000',17,45,10);
insert into utB values('20030101 01:13:18.000',17,45,10);
insert into utB values('20030201 01:13:19.000',18,45,10);
insert into utB values('20030301 01:13:20.000',18,45,10);
insert into utB values('20030401 01:13:21.000',18,46,10);
insert into utB values('20030501 01:13:22.000',18,46,10);
insert into utB values('20030611 01:13:23.000',19,44,10);
insert into utB values('20030101 01:13:24.000',19,44,10);
insert into utB values('20030101 01:13:25.000',19,45,10);
insert into utB values('20030101 01:13:26.000',19,45,10);
insert into utB values('20030201 01:13:27.000',20,45,10);
insert into utB values('20030301 01:13:28.000',20,45,10);
insert into utB values('20030401 01:13:29.000',20,46,10);
insert into utB values('20030501 01:13:30.000',20,46,10);
insert into utB values('20030201 01:13:31.000',21,49,50);
insert into utB values('20030202 01:13:32.000',21,49,50);
insert into utB values('20030203 01:13:33.000',21,50,50);
insert into utB values('20030204 01:13:34.000',21,50,50);
insert into utB values('20030205 01:13:35.000',21,48,1);
insert into utB values('20000101 01:13:36.000',22,50,50);
insert into utB values('20010101 01:13:37.000',22,50,50);
insert into utB values('20020101 01:13:38.000',22,51,50);
insert into utB values('20020601 01:13:39.000',22,51,50);
insert into utB values('20030101 01:13:05.000',4,37,185);

drop table if exists outcomes;
drop table if exists ships;
drop table if exists classes;
drop table if exists battles;

CREATE TABLE Battles (
	name varchar (20) NOT NULL ,
	date timestamp NOT NULL 
) 
;

CREATE TABLE Classes (
	class varchar (50) NOT NULL ,
	type varchar (2) NOT NULL ,
	country varchar (20) NOT NULL ,
	numGuns smallint NULL ,
	bore real NULL ,
	displacement int NULL 
) 
;

CREATE TABLE Ships (
	name varchar (50) NOT NULL ,
	class varchar (50) NOT NULL ,
	launched smallint NULL 
) 
;

CREATE TABLE Outcomes (
	ship varchar (50) NOT NULL ,
	battle varchar (20) NOT NULL ,
	result varchar (10) NOT NULL 
) 
;

                                                                                                                                                                                                                                                               
----Classes------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Classes values('Bismarck','bb','Germany',8,15,42000);
insert into Classes values('Iowa','bb','USA',9,16,46000);
insert into Classes values('Kongo','bc','Japan',8,14,32000);
insert into Classes values('North Carolina','bb','USA',12,16,37000);
insert into Classes values('Renown','bc','Gt.Britain',6,15,32000);
insert into Classes values('Revenge','bb','Gt.Britain',8,15,29000);
insert into Classes values('Tennessee','bb','USA',12,14,32000);
insert into Classes values('Yamato','bb','Japan',9,18,65000);



                                                                                                                                                                                                                                                                 
----Battles------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Battles values('Guadalcanal','19421115 00:00:00.000');
insert into Battles values('North Atlantic','19410525 00:00:00.000');
insert into Battles values('North Cape','19431226 00:00:00.000');
insert into Battles values('Surigao Strait','19441025 00:00:00.000');
insert into battles values ('#Cuba62a'   , '19621020');
insert into battles values ('#Cuba62b'   , '19621025');



                                                                                                                                                                                                                                                                 
----Ships------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Ships values('California','Tennessee',1921);
insert into Ships values('Haruna','Kongo',1916);
insert into Ships values('Hiei','Kongo',1914);
insert into Ships values('Iowa','Iowa',1943);
insert into Ships values('Kirishima','Kongo',1915);
insert into Ships values('Kongo','Kongo',1913);
insert into Ships values('Missouri','Iowa',1944);
insert into Ships values('Musashi','Yamato',1942);
insert into Ships values('New Jersey','Iowa',1943);
insert into Ships values('North Carolina','North Carolina',1941);
insert into Ships values('Ramillies','Revenge',1917);
insert into Ships values('Renown','Renown',1916);
insert into Ships values('Repulse','Renown',1916);
insert into Ships values('Resolution','Renown',1916);
insert into Ships values('Revenge','Revenge',1916);
insert into Ships values('Royal Oak','Revenge',1916);
insert into Ships values('Royal Sovereign','Revenge',1916);
insert into Ships values('Tennessee','Tennessee',1920);
insert into Ships values('Washington','North Carolina',1941);
insert into Ships values('Wisconsin','Iowa',1944);
insert into Ships values('Yamato','Yamato',1941);
insert into Ships values('South Dakota','North Carolina',1941) ;




                                                                                                                                                                                                                                                                 
----Outcomes------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Outcomes values('Bismarck','North Atlantic','sunk');
insert into Outcomes values('California','Surigao Strait','OK');
insert into Outcomes values('Duke of York','North Cape','OK');
insert into Outcomes values('Fuso','Surigao Strait','sunk');
insert into Outcomes values('Hood','North Atlantic','sunk');
insert into Outcomes values('King George V','North Atlantic','OK');
insert into Outcomes values('Kirishima','Guadalcanal','sunk');
insert into Outcomes values('Prince of Wales','North Atlantic','damaged');
insert into Outcomes values('Rodney','North Atlantic','OK');
insert into Outcomes values('Schamhorst','North Cape','sunk');
insert into Outcomes values('South Dakota','Guadalcanal','damaged');
insert into Outcomes values('Tennessee','Surigao Strait','OK');
insert into Outcomes values('Washington','Guadalcanal','OK');
insert into Outcomes values('West Virginia','Surigao Strait','OK');
insert into Outcomes values('Yamashiro','Surigao Strait','sunk');
insert into Outcomes values('California','Guadalcanal','damaged');'''

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect('db')

In [ ]:
cur = conn.cursor()

In [ ]:
cur.executescript(sql)

## Решение задач

In [ ]:
# импортируем Pandas для работы с датафреймами
import pandas as pd

In [ ]:
# создадим функцию, которая будет передавать результат sql-запроса в Pandas-Dataframe

def select(sql):
  return pd.read_sql(sql,conn)

###  Базы данных
на sql-ex.ru есть несколько баз данных.

По ссылке можно ознакомиться со всеми базами: https://sql-ex.ru/help/select13.php#db_1

Под спойлером можно ознакомиться с подробным описанием таблиц

#### База данных "Компьютерная фирма"
Схема БД состоит из четырех таблиц:
1. **Product** (maker, model, type)
2. **PC** (code, model, speed, ram, hd, cd, price)
3. **Laptop** (code, model, speed, ram, hd, price, screen)
4. **Printer** (code, model, color, type, price)

Схема: https://sql-ex.ru/help/select13.php#db_1

Таблица Product представляет производителя (maker), номер модели (model) и тип ('PC' - ПК, 'Laptop' - ПК-блокнот или 'Printer' - принтер). Предполагается, что номера моделей в таблице Product уникальны для всех производителей и типов продуктов. В таблице PC для каждого ПК, однозначно определяемого уникальным кодом – code, указаны модель – model (внешний ключ к таблице Product), скорость - speed (процессора в мегагерцах), объем памяти - ram (в мегабайтах), размер диска - hd (в гигабайтах), скорость считывающего устройства - cd (например, '4x') и цена - price. Таблица Laptop аналогична таблице РС за исключением того, что вместо скорости CD содержит размер экрана -screen (в дюймах). В таблице Printer для каждой модели принтера указывается, является ли он цветным - color ('y', если цветной), тип принтера - type (лазерный – 'Laser', струйный – 'Jet' или матричный – 'Matrix') и цена - price.

#### База данных "Фирма вторсырья"
Схема БД состоит из четырех таблиц:
1. **Income_o** (point, date, inc)
2. **Outcome_o** (point, date, out)
3. **Income** (code, point, date, inc)
4. **Outcome** (code, point, date, out)

Схема: https://sql-ex.ru/help/select13.php#db_2

Фирма имеет несколько пунктов приема вторсырья. Каждый пункт получает деньги для их выдачи сдатчикам вторсырья. Сведения о получении денег на пунктах приема записываются в таблицу:
Income_o(point, date, inc)

Первичным ключом является (point, date).

При этом в столбец date записывается только дата (без времени), т.е. прием денег (inc) на каждом пункте производится не чаще одного раза в день. Сведения о выдаче денег сдатчикам вторсырья записываются в таблицу:
Outcome_o(point, date, out)
В этой таблице также первичный ключ (point, date) гарантирует отчетность каждого пункта о выданных деньгах (out) не чаще одного раза в день.

В случае, когда приход и расход денег может фиксироваться несколько раз в день, используется другая схема с таблицами, имеющими первичный ключ code:
Income(code, point, date, inc)
Outcome(code, point, date, out)
Здесь также значения столбца date не содержат времени.

#### База данных "Корабли"
Схема БД состоит из четырех таблиц:
1. **Classes** (class, type, country, numGuns, bore, displacement)
2. **Ships** (name, class, launched)
3. **Battles** (name, date)
4. **Outcomes** (ship, battle, result)

Схема: https://sql-ex.ru/help/select13.php#db_3

Корабли в «классах» построены по одному и тому же проекту, и классу присваивается либо имя первого корабля, построенного по данному проекту, либо названию класса дается имя проекта, которое не совпадает ни с одним из кораблей в БД. Корабль, давший название классу, называется головным.

Отношение Classes содержит имя класса, тип (bb для боевого (линейного) корабля или bc для боевого крейсера), страну, в которой построен корабль, число главных орудий, калибр орудий (диаметр ствола орудия в дюймах) и водоизмещение ( вес в тоннах). В отношении Ships записаны название корабля, имя его класса и год спуска на воду. В отношение Battles включены название и дата битвы, в которой участвовали корабли, а в отношении Outcomes – результат участия данного корабля в битве (потоплен-sunk, поврежден - damaged или невредим - OK).

Замечания. 1) В отношение Outcomes могут входить корабли, отсутствующие в отношении Ships. 2) Потопленный корабль в последующих битвах участия не принимает.

### Задача № 1
https://sql-ex.ru/learn_exercises.php?LN=1

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd.

In [ ]:
# Сначала посмотрим на саму таблицу с ПК

sql = '''select * from pc limit 5'''
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x    600
1     2  1121    750  128  14.0  40x    850
2     3  1233    500   64   5.0  12x    600
3     4  1121    600  128  14.0  40x    850
4     5  1121    600  128   8.0  40x    850

In [ ]:
# Напишем сам запрос

sql = '''
select model, speed, hd -- выбираем номер модели, скорость и объем жесткого диска
from pc
where price < 500 --фильтруем таблицу по цене менее 500$
'''

select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

***
### Задача № 2
https://sql-ex.ru/learn_exercises.php?LN=2

Найдите производителей принтеров. Вывести: maker

In [ ]:
# Сначала посмотрим на саму таблицу

sql = '''select * from product limit 5'''
select(sql)

maker model     type
0     B  1121       PC
1     A  1232       PC
2     A  1233       PC
3     E  1260       PC
4     A  1276  Printer

In [ ]:
# Напишем сам запрос

sql = '''
SELECT DISTINCT maker -- чтобы производители не дублировались, используем дистинкт
FROM Product  
WHERE type = 'Printer' -- берем только те записи из таблицы, где тип "принтер"
'''

select(sql)

maker
0     A
1     D
2     E

***
### Задача № 3
https://sql-ex.ru/learn_exercises.php?LN=3

Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

In [ ]:
# Сначала посмотрим на саму таблицу

sql = '''select * from laptop limit 5'''
select(sql)

code model  speed  ram    hd  price  screen
0     1  1298    350   32   4.0    700      11
1     2  1321    500   64   8.0    970      12
2     3  1750    750  128  12.0   1200      14
3     4  1298    600   64  10.0   1050      15
4     5  1752    750  128  10.0   1150      14

In [ ]:
# Напишем сам запрос

sql = '''
select model, ram, screen -- выбираем нужные характеристики
from laptop
where price > 1000 -- фильтруем таблицу по стоимости больше 1000$

'''

select(sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

***
### Задача № 4
https://sql-ex.ru/learn_exercises.php?LN=4

Найдите все записи таблицы Printer для цветных принтеров.

In [ ]:
# Сначала посмотрим на саму таблицу

sql = '''select * from printer limit 5'''
select(sql)

code model color    type  price
0     1  1276     n   Laser    400
1     2  1433     y     Jet    270
2     3  1434     y     Jet    290
3     4  1401     n  Matrix    150
4     5  1408     n  Matrix    270

In [ ]:
# Напишем сам запрос

sql = '''
select *
from printer
where color = 'y' -- фильтруем таблицу по цветным принтерам
'''

select(sql)

code model color type  price
0     2  1433     y  Jet    270
1     3  1434     y  Jet    290

***
### Задача № 5
https://sql-ex.ru/learn_exercises.php?LN=5

Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [ ]:
# Сначала посмотрим на саму таблицу

sql = '''select * from pc limit 5'''
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x    600
1     2  1121    750  128  14.0  40x    850
2     3  1233    500   64   5.0  12x    600
3     4  1121    600  128  14.0  40x    850
4     5  1121    600  128   8.0  40x    850

In [ ]:
# Напишем сам запрос

sql = '''
select model, speed, hd -- выбираем нужные характеристики
from pc
where price < 600 -- фильтруем таблицу по цене менее 600$
and cd in ('12x', '24x') -- и выбираем только те записи, в которых скорость cd 12х или 24х ("что-то из")
'''

select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

***
### Задача № 6
https://sql-ex.ru/learn_exercises.php?LN=6

Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.

In [ ]:
# Сначала посмотрим на саму таблицу с ПК

sql = '''select * from pc limit 5'''
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x    600
1     2  1121    750  128  14.0  40x    850
2     3  1233    500   64   5.0  12x    600
3     4  1121    600  128  14.0  40x    850
4     5  1121    600  128   8.0  40x    850

In [ ]:
# Напишем сам запрос

sql = '''

-- 3. для каждого производителя найдем скорость всех произведенных им лэптопов с объемом hd не менее 10ГБ
select distinct maker, speed

-- 1. соединим таблицы laptop и product, чтобы можно было отфильтровать производителя по скорости произведенных им лэптопов
from laptop l join product p on l.model = p.model

-- 2. фильтруем полученную таблицу по объему hd не менее 10ГБ
where l.hd >= 10

-- 4. отсортируем по скорости процессора по возрастанию
order by speed
'''

select(sql)

maker  speed
0     A    450
1     A    600
2     B    750
3     A    750

***
### Задача № 7
https://sql-ex.ru/learn_exercises.php?LN=7

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B.

Решим задачу в 3 шага:
1. Соберем общую таблицу со списком всех моделей всех продуктов и стоимостью каждой модели
2. Добавим к таблице информацию о производителях каждой модели
3. Выберем только те модели и цены, которые относятся к производителю B.

In [ ]:
# Собираем общую таблицу

# Из таблиц pc, laptop & printer собираем номера всех моделей и их цены
# И затем присоединяем строки снизу друг к другу для получения общего списка

sql = '''
SELECT model, price 
FROM PC 

UNION

SELECT model, price 
FROM Laptop

UNION

SELECT model, price 
FROM Printer
'''

select(sql)

model  price
0   1121    850
1   1232    350
2   1232    400
3   1232    600
4   1233    600
5   1233    950
6   1233    970
7   1233    980
8   1260    350
9   1276    400
10  1288    400
11  1298    700
12  1298    950
13  1298   1050
14  1321    970
15  1401    150
16  1408    270
17  1433    270
18  1434    290
19  1750   1200
20  1752   1150

In [ ]:
# выполним действия 2 и 3

sql = '''

-- 3. выберем все номера моделей и их цены из полученной таблицы
SELECT a.model, price 

-- 1. Полученную на 1 шаге таблицу соединим с таблицей product по общему полю model
FROM (SELECT model, price 
 FROM PC 
 UNION
 SELECT model, price 
  FROM Laptop
 UNION
 SELECT model, price 
 FROM Printer
 ) AS a JOIN -- сохраняем результат UNION как таблицу a
 Product p ON a.model = p.model -- джойним эту таблицу к таблице product
 
-- 2. Фильтруем полученную таблицу по производителю В
WHERE p.maker = 'B'
'''

select(sql)

model  price
0  1121    850
1  1750   1200

***
### Задача № 8
https://sql-ex.ru/learn_exercises.php?LN=8

Найдите производителя, выпускающего ПК, но не ПК-блокноты (не лэптопы).

In [ ]:
sql = '''
select distinct maker -- 3. выберем уникальных производителей

from product -- 1. возьмем таблицу с производителями

where type='PC' -- 2.1 отфильтруем её по типу PC

and maker not in   -- 2.2 отфильтруем по производителю, который не находится в списке ниже

-- 2.3 список со всеми производителями, у которых среди продуктов встречаются лэптопы
(select maker from product where type = 'Laptop')
'''

select(sql)

maker
0     E

***
### Задача № 9
https://sql-ex.ru/learn_exercises.php?LN=9

Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

In [ ]:
sql = '''

-- 3. выберем уникальных производителей из полученной таблицы
SELECT distinct maker

-- 1. соеденим таблицы product и pc по общему полю model
FROM product pr join pc pc on pr.model = pc.model

-- 2. оставим только те записи, у которых значение поля speed не меньше 450
WHERE speed >= 450
'''

select(sql)

maker
0     A
1     B
2     E

***
### Задача № 10
https://sql-ex.ru/learn_exercises.php?LN=10

Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price

In [ ]:
sql = '''
-- 3. из полученной таблицы выберем номера моделей и их цену
SELECT model, price  

-- 1. возьмем таблицу с принтерами
FROM Printer  

-- 2. отфильтруем таблицу с помощью подзапроса, который отдает цену самого дорого принтера
WHERE price = (SELECT MAX(price) 
               FROM Printer
               )
'''

select(sql)

model  price
0  1276    400
1  1288    400

***
### Задача № 11
https://sql-ex.ru/learn_exercises.php?LN=11

Найдите среднюю скорость ПК

In [ ]:
sql = '''
select AVG(speed) as Avg_speed
from pc
'''

select(sql)

Avg_speed
0  608.333333

***
### Задача № 12
https://sql-ex.ru/learn_exercises.php?LN=12

Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.

In [ ]:
sql = '''
SELECT AVG(speed)
FROM laptop
WHERE price > 1000
'''

select(sql)

AVG(speed)
0       700.0

***
### Задача № 13
https://sql-ex.ru/learn_exercises.php?LN=13

Найдите среднюю скорость ПК, выпущенных производителем A.

In [ ]:
sql = '''
-- 3. посчитаем среднюю скорость пк, произведенных А
SELECT AVG(speed) as avg_speed

-- 2. соеденим таблицу pc с таблицей product по общему полю model
-- чтобы для каждого ПК был известен производитель
FROM pc pc join product pr on pc.model = pr.model

-- 3. отфильтруем таблицу по производителю А
WHERE pr.maker = 'A'
'''

select(sql)

avg_speed
0     606.25

***
### Задача № 14
https://sql-ex.ru/learn_exercises.php?LN=14

Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.

In [ ]:
sql = '''

-- 3. выберем класс, имя и страну кораблей, соответствующих условиям задачи
SELECT s.class, name, country

-- 1. соеденим таблицу ships с таблицей classes по общему полю
FROM ships s join classes c on s.class = c.class

-- 2. отфильтруем таблицу по количеству орудий
WHERE numGuns >= 10

'''

select(sql)

class            name country
0  North Carolina  North Carolina     USA
1  North Carolina    South Dakota     USA
2  North Carolina      Washington     USA
3       Tennessee      California     USA
4       Tennessee       Tennessee     USA

***
### Задача № 15
https://sql-ex.ru/learn_exercises.php?LN=15

Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [ ]:
sql = '''

-- 2. из неё выбираем все hd
SELECT hd

-- 1. выбираем таблицу pc
FROM pc

-- 3. группируем все hd
GROUP BY (hd)

-- 4. оставляем только те hd (размеры жестких дисков), для которых можно насчитать от 2х моделей
HAVING COUNT(model) >= 2
'''

select(sql)

hd
0   5.0
1   8.0
2  10.0
3  14.0
4  20.0

***
### Задача № 16
https://sql-ex.ru/learn_exercises.php?LN=16

Найдите пары моделей PC, имеющих одинаковые скорость и RAM. 

В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i).

Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.

Для решения этой задачи нам нужно сравнить записи в одной и той же таблице. <br>
По сути чтобы иметь возможность это делать, нужно обращаться к двум разным таблицам с одним содержанием. <br>
Для этого будем забирать записи из таблицы pc с названием "а" и названием "b".

Вместе они выглядят вот так.

In [ ]:
sql = '''
SELECT *
FROM pc a, pc b
LIMIT 5
'''

select(sql)

code  model  speed ram   hd   cd  ...  model  speed  ram    hd   cd  price
0     1   1232    500  64  5.0  12x  ...   1232    500   64   5.0  12x    600
1     1   1232    500  64  5.0  12x  ...   1121    750  128  14.0  40x    850
2     1   1232    500  64  5.0  12x  ...   1233    500   64   5.0  12x    600
3     1   1232    500  64  5.0  12x  ...   1121    600  128  14.0  40x    850
4     1   1232    500  64  5.0  12x  ...   1121    600  128   8.0  40x    850

[5 rows x 14 columns]

При таком синтаксисе FROM для каждой строки из первой таблицы (а) мы подставляем значения второй таблицы (b). Так у нас появляется возможность сравнивать каждую запись в таблице с любой другой записью в таблице (это называется декартово произведение).

Напишем полный запрос.

In [ ]:
sql = '''

-- 3. Выберем уникальные номера моделей и укажем для них скорость и объем памяти
SELECT DISTINCT a.model, b.model, a.speed, a.ram

-- 1. укажем, что хотим собрать записи из 2х таблицу сразу
FROM pc a, pc b

-- 2. укажем, что хотим забирать только те строки, где совпадают значения:
WHERE a.ram = b.ram
AND a.speed = b.speed
AND a.model > b.model
'''

select(sql)

model model  speed  ram
0  1233  1232    500   64
1  1233  1121    750  128
2  1260  1232    500   32

***
### Задача № 17
https://sql-ex.ru/learn_exercises.php?LN=17

Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed

In [ ]:
sql = '''

-- 3. забираем нужные строки
SELECT  DISTINCT p.type, l.model, l.speed

-- 1. ко всем записям таблицы laptop добавляем соответствующие им строки таблицы
-- product (это нужно, чтобы забрать значения поля type для всех лэптопов)
FROM laptop l left join product p on l.model = p.model

-- 2. фильтруем таблицу по условию "скорость меньше чем скорость всех ПК)
-- для сравнения используем подзапрос, который дает список всех speed таблицы пк
WHERE l.speed NOT IN (SELECT pc.speed FROM pc)

'''

select(sql)

type model  speed
0  Laptop  1298    350

Выдача верная, но условие для фильрации неправильное.

Правильное услови "WHERE l.speed < ALL (SELECT ...)". Но Collab почему-то не принимает его (скорее всего из-за другого SQL).

Решение NOT IN неправильное, так как l.speed по такому условию может оказаться и выше, чем все значения списка.

***
### Задача № 18
https://sql-ex.ru/learn_exercises.php?LN=18

Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [ ]:
sql = '''

-- 3. выберем уникальных производителей и цены их самых дешевых принтеров 
SELECT DISTINCT maker, price

-- 1. соединяем таблицы printer & product по общему полю model, чтобы сопоставить производителей с их принтерами
FROM printer JOIN product
ON printer.model = product.model

-- 2. фильтруем таблицу по условиям:
-- 2.1 цветной принтер
WHERE (color = 'y')

-- 2.2 и цена равна минимальной цене в таблице printer отфильтрованной по цветным
AND price = (
            SELECT MIN(price)
            FROM printer
            WHERE color = 'y'
            )

'''

select(sql)

maker  price
0     D    270

***
### Задача № 19
https://sql-ex.ru/learn_exercises.php?LN=19

Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [ ]:
sql = '''

-- 3.  выберем каждого производителя и посчитаем средний размер экрана у всех лэптов по каждому производителю
SELECT maker, AVG(screen) as avg_screen

-- 1. к таблице laptop добавим информацию о производителях
FROM laptop l LEFT JOIN product p ON l.model = p.model

-- 2. сгруппируем таблицу по производителям
GROUP BY maker
'''

select(sql)

maker  avg_screen
0     A        13.0
1     B        14.0
2     C        12.0

***
### Задача № 20
https://sql-ex.ru/learn_exercises.php?LN=20

Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [ ]:
sql = '''

-- 5. выберем производителей и посчитаем кол-во произведенных каждым моделей
SELECT maker, COUNT(model) as Count_Model

-- 1. укажем таблицу
FROM product

-- 2. отфильтруем таблицу по условию тип = ПК
WHERE type = 'PC'

-- 3. сгруппируем данные по производителю
GROUP BY maker

-- 4. выберем только те записи, в которых у производителя насчитывается не менее 3х моделей
HAVING COUNT(model) >= 3

'''

select(sql)

maker  Count_Model
0     E            3

***

***
### Задача № 21
https://sql-ex.ru/learn_exercises.php?LN=21

Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [ ]:
sql = '''

-- 3. получим список производителей и максимальную цену ПК у каждого из них
SELECT maker, MAX(price) as Max_price

-- 1. ко всем записям таблице pc добавим информацию о производителе
FROM pc left join product p on pc.model = p.model

-- 2. сгруппируем записи по производителю
GROUP BY maker
'''

select(sql)

maker  Max_price
0     A        980
1     B        850
2     E        350

***
### Задача № 22
https://sql-ex.ru/learn_exercises.php?LN=22

Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [ ]:
sql = '''

-- 4. найдем среднюю цену всех ПК со скоростью выше 600 МГц (на каждую скорость процессора)
SELECT speed, AVG(price) as Avg_price

-- 1. выберем таблицу ПК
FROM pc

-- 2. оставим только записи о тех ПК, у которых скорость больше 600
WHERE speed > 600

-- 3. сгруппируем оставшиеся записи по скорости
GROUP BY speed

'''

select(sql)

speed  Avg_price
0    750      900.0
1    800      970.0
2    900      980.0

***

***
### Задача № 23
https://sql-ex.ru/learn_exercises.php?LN=23

Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker

In [ ]:
sql = '''
-- 4. выберем оставшихся производителей
SELECT DISTINCT maker

-- 1. соединим таблицу с производителями с таблицей ПК
FROM product p JOIN pc ON p.model=pc.model

-- 2. отфильтруем таблицу по двум условиям:

-- 2.1 скорость процессора выше 750 МГц
WHERE speed >= 750

-- 2.2. И производителей также находится в списке тех, кто производит лэптопы со скоростью процессора от 750 МГц
AND maker IN

-- 2.2.1 список получаем с помощью подзапроса, который отдает список производителей лэптопов по условию
( SELECT maker
FROM product p JOIN laptop l ON p.model=l.model
WHERE speed>=750)

'''

select(sql)

maker
0     B
1     A

***
### Задача № 24
https://sql-ex.ru/learn_exercises.php?LN=24

Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [ ]:
sql = '''
SELECT model

-- 1. получим общий список всех моделей разных товаров и их цены
FROM (
      SELECT model, price
      FROM pc
      UNION
      SELECT model, price
      FROM Laptop
      UNION
      SELECT model, price
      FROM Printer
      ) t1

-- 2. оставим только те строки списка, где цена соответствует максимальной цене в этом же списке 
WHERE price = (
              SELECT MAX(price) -- выбираем максимальную цену
              FROM (            -- из того же самого списка (только без моделей)
                    SELECT price
                    FROM pc
                    UNION
                    SELECT price
                    FROM Laptop
                    UNION
                    SELECT price
                    FROM Printer
                    ) t2
              )
'''

select(sql)

model
0  1750

***
### Задача № 25
https://sql-ex.ru/learn_exercises.php?LN=25

Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker

In [ ]:
sql = '''

-- 4. выбираем всех производителей из итоговой таблицы
SELECT DISTINCT maker

-- 1. выбираем таблицу с производителями
FROM product

-- 2. с помощью подзапросов выбираем нужных производителей по заданным условиям
WHERE model IN (              
                SELECT model  -- 2.1 выбираем модели ПК, в которых
                FROM pc
                WHERE ram = ( -- ram равна минимальной ram среди всех ПК
                              SELECT MIN(ram)
                              FROM pc
                            )
                AND speed = ( 
                              SELECT MAX(speed) -- 2.2 скорость равна
                              FROM pc
                              WHERE ram = (     -- минимальной скорости всех ПК
                                            SELECT MIN(ram)
                                            FROM pc
                                          )
                             )
                  )

-- 3. выбираем производителя, который также производит принтеры (находится среди производителей принтеров)
AND maker IN (
              SELECT maker
              FROM product
              WHERE type='Printer'
              )

'''

select(sql)

maker
0     A
1     E

***
### Задача № 26
https://sql-ex.ru/learn_exercises.php?LN=26

Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.

In [ ]:
sql = '''
SELECT AVG(price) as AVG_price

-- 1. формируем таблицу со всеми ценами лэптопов и ПК с помощью соединения двух подзапросов
-- оставляем в ней model, чтобы по этому полю добавить производителя

FROM (SELECT model, price -- тут собираем модели и цену всех ПК
      FROM pc

      UNION ALL -- соединяем таблицы, чтобы получилась одна таблица с двумя колонками

      SELECT model, price -- тут собираем модели и цену всех лэптопов
      FROM laptop) as t

JOIN product p on t.model = p.model -- к полученной таблице добавляем информацию о производителе

-- 2. фильтруем таблицу по производителю A
WHERE maker = 'A'

'''

select(sql)

AVG_price
0  754.166667

***
### Задача № 27
https://sql-ex.ru/learn_exercises.php?LN=27

Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры.

Вывести: maker, средний размер HD.

In [ ]:
sql = '''

-- 4. выберем производителей и средний размер жесткого диска
SELECT maker,
       AVG(hd) as Avg_hd

-- 1. к таблице ПК добавим информацию о производителеях
FROM pc JOIN product on pc.model = product.model

-- 2. Отфильтруем таблицу по производителям с помощью подзапроса
-- Условие: производитель ПК находится среди производителей принтеров
WHERE maker IN (
                SELECT maker -- выберем производителей, которые производят принтеры
                FROM product
                WHERE type = 'Printer')

-- 3. сгруппируем итоговую таблицу по производителям
GROUP BY maker
'''

select(sql)

maker  Avg_hd
0     A   14.75
1     E   10.00

***
### Задача № 28
https://sql-ex.ru/learn_exercises.php?LN=28

Используя таблицу Product, определить количество производителей, выпускающих по одной модели.

In [ ]:
sql = '''

-- 3. считаем кол-во производителей в итоговой таблице
SELECT COUNT(maker) as makers_number

-- 1. возьмем таблицу с производителями
FROM product

-- 2. отфильтруем по условию "производители, которые производят только одну модель)
WHERE maker in
(
  SELECT maker FROM product -- выбираем всех производителей
  GROUP BY maker
  HAVING COUNT(model) = 1 -- фильтруем по условию "кол-во моделей у производителя = 1"
)
'''

select(sql)

makers_number
0              1

***
### Задача № 29
https://sql-ex.ru/learn_exercises.php?LN=29

Приход и расход денег на каждом пункте приема фиксируется не чаще одного раза в день [т.е. первичный ключ (пункт, дата)].

Написать запрос с выходными данными (пункт, дата, приход, расход). Использовать таблицы Income_o и Outcome_o.

In [ ]:
sql = '''
SELECT t.point, -- выбираем каждую точку и дату и для них находим общую сумму расходов и доходов
       t.date,
       SUM(t.inc) as inc,
       SUM(t.out) as out

-- 1. соберем общую таблицу расходов и приходов с помощью UNION 
FROM (
      SELECT point, date, inc, null as out -- 1.1 из таблицы с приходами получим все записи с приходами и создаем столбец с расходами, где будет null (это нужно для работы UNION)
      FROM Income_o

      UNION -- 1.3 соединяем обе таблицы в один общий список доходов и расходов на каждую дату в каждой точке

      SELECT point, date, null as inc, out -- 1.2 из таблицы с расходами получим все записи и сделаем столбец inc, содержащий null, чтобы таблицы были одинаковы и UNION работал
      FROM Outcome_o
     ) as t

-- 2. группируем данные из общей таблицы по точке и дате
GROUP BY t.point, t.date
'''

select(sql)

point                   date      inc       out
0       1  20010314 00:00:00.000      NaN  15348.00
1       1  20010322 00:00:00.000  15000.0       NaN
2       1  20010323 00:00:00.000  15000.0       NaN
3       1  20010324 00:00:00.000   3400.0   3663.00
4       1  20010326 00:00:00.000      NaN   1221.00
5       1  20010328 00:00:00.000      NaN   2075.00
6       1  20010329 00:00:00.000      NaN   2004.00
7       1  20010411 00:00:00.000      NaN   3195.04
8       1  20010413 00:00:00.000   5000.0   4490.00
9       1  20010427 00:00:00.000      NaN   3110.00
10      1  20010511 00:00:00.000   4500.0   2530.00
11      2  20010322 00:00:00.000  10000.0   1440.00
12      2  20010324 00:00:00.000   1500.0       NaN
13      2  20010329 00:00:00.000      NaN   7848.00
14      2  20010402 00:00:00.000      NaN   2040.00
15      3  20010913 00:00:00.000  11500.0   1500.00
16      3  20010914 00:00:00.000      NaN   2300.00
17      3  20011002 00:00:00.000  18000.0       NaN
18      3  20020916 00:00:00.000      NaN   2150.00

***
### Задача № 30
https://sql-ex.ru/learn_exercises.php?LN=30

Приход и расход денег на каждом пункте приема фиксируется произвольное число раз (первичным ключом в таблицах является столбец code).

Получить таблицу, в которой каждому пункту за каждую дату выполнения операций будет соответствовать одна строка.

Вывод: point, date, суммарный расход пункта за день (out), суммарный приход пункта за день (inc).

Отсутствующие значения считать неопределенными (NULL).

In [ ]:
sql = '''

-- . на каждую дату в каждой точке считаем итоговые суммы расхода и прихода
SELECT point,
       date,
       SUM(sum_out) as sum_out,
       SUM(sum_inc) as sum_inc

-- 1. формируем общую таблицу расхода и прихода с помощью UNION
FROM (
      SELECT point, date, SUM(inc) as sum_inc, null as sum_out -- 1.1 из таблицы с приходом находим сумму дохода на каждый день в каждой точке
                                                               -- с помощью "null as sum_out" создаем столбец с расходом, в котором будет null
                                                               --далее в этот столбец попадут значения из таблицы Outcome
      FROM Income
      GROUP BY point, date  -- группируем данные по точке и дате

      UNION -- 1.3 соединяем обе таблицы внутри подзапроса, исключая дубликаты

      SELECT point, date, null as sum_inc, SUM(out) as sum_out -- 1.2 из таблицы с расходами находим сумму расходов на каждый день в каждой точке
                                                               -- здесь также создаем пустой столбец "sum_inc", заполненный null
      FROM Outcome
      GROUP BY point, date
      ) as t  

-- 2. Далее мы получаем таблицу в которой повторяются точки и даты, т.к. как на каждую точку и дату у нас есть расходы и доходы
-- группируем таблицу еще раз по точке и дате, чтобы избежать дублирования строк

GROUP BY point, date -- так в каждой строке будет точка, дата расход и приход
ORDER BY point -- отсортируем по номеру точки для удобства
'''

select(sql)

point                   date   sum_out  sum_inc
0       1  20010314 00:00:00.000  15348.00      NaN
1       1  20010322 00:00:00.000       NaN  30000.0
2       1  20010323 00:00:00.000       NaN  15000.0
3       1  20010324 00:00:00.000   7163.00   7000.0
4       1  20010326 00:00:00.000   1221.00      NaN
5       1  20010328 00:00:00.000   2075.00      NaN
6       1  20010329 00:00:00.000   4010.00      NaN
7       1  20010411 00:00:00.000   3195.04      NaN
8       1  20010413 00:00:00.000   4490.00  10000.0
9       1  20010427 00:00:00.000   3110.00      NaN
10      1  20010511 00:00:00.000   2530.00   4500.0
11      2  20010322 00:00:00.000   2880.00  10000.0
12      2  20010324 00:00:00.000       NaN   3000.0
13      2  20010329 00:00:00.000   7848.00      NaN
14      2  20010402 00:00:00.000   2040.00      NaN
15      3  20010913 00:00:00.000   2700.00   3100.0
16      3  20010914 00:00:00.000   1150.00      NaN